remote_theme: mmistakes/minimal-mistakes@4.22.0
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
title                    : "Azure usergroup Norway"